apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  template:
    spec:
      containers:
        - name: backend
          envFrom:
            - secretRef:
                name: todo-backend-secret
